# Python stubs generated by omniidl from student.idl
# DO NOT EDIT THIS FILE!

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA


_omnipy.checkVersion(4,2, __file__, 1)

try:
    property
except NameError:
    def property(*args):
        return None


#
# Start of module "school"
#
__name__ = "school"
_0_school = omniORB.openModule("school", r"student.idl")
_0_school__POA = omniORB.openModule("school__POA", r"student.idl")


# struct Etudiant
_0_school.Etudiant = omniORB.newEmptyClass()
class Etudiant (omniORB.StructBase):
    _NP_RepositoryId = "IDL:school/Etudiant:1.0"

    def __init__(self, matricule, nom, sexe, promotion, dateNaissance):
        self.matricule = matricule
        self.nom = nom
        self.sexe = sexe
        self.promotion = promotion
        self.dateNaissance = dateNaissance

_0_school.Etudiant = Etudiant
_0_school._d_Etudiant  = (omniORB.tcInternal.tv_struct, Etudiant, Etudiant._NP_RepositoryId, "Etudiant", "matricule", (omniORB.tcInternal.tv_string,0), "nom", (omniORB.tcInternal.tv_string,0), "sexe", (omniORB.tcInternal.tv_string,0), "promotion", (omniORB.tcInternal.tv_string,0), "dateNaissance", (omniORB.tcInternal.tv_string,0))
_0_school._tc_Etudiant = omniORB.tcInternal.createTypeCode(_0_school._d_Etudiant)
omniORB.registerType(Etudiant._NP_RepositoryId, _0_school._d_Etudiant, _0_school._tc_Etudiant)
del Etudiant

# typedef ... EtudiantSeq
class EtudiantSeq:
    _NP_RepositoryId = "IDL:school/EtudiantSeq:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_school.EtudiantSeq = EtudiantSeq
_0_school._d_EtudiantSeq  = (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:school/Etudiant:1.0"], 0)
_0_school._ad_EtudiantSeq = (omniORB.tcInternal.tv_alias, EtudiantSeq._NP_RepositoryId, "EtudiantSeq", (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:school/Etudiant:1.0"], 0))
_0_school._tc_EtudiantSeq = omniORB.tcInternal.createTypeCode(_0_school._ad_EtudiantSeq)
omniORB.registerType(EtudiantSeq._NP_RepositoryId, _0_school._ad_EtudiantSeq, _0_school._tc_EtudiantSeq)
del EtudiantSeq

# interface GestionEtudiants
_0_school._d_GestionEtudiants = (omniORB.tcInternal.tv_objref, "IDL:school/GestionEtudiants:1.0", "GestionEtudiants")
omniORB.typeMapping["IDL:school/GestionEtudiants:1.0"] = _0_school._d_GestionEtudiants
_0_school.GestionEtudiants = omniORB.newEmptyClass()
class GestionEtudiants :
    _NP_RepositoryId = _0_school._d_GestionEtudiants[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_school.GestionEtudiants = GestionEtudiants
_0_school._tc_GestionEtudiants = omniORB.tcInternal.createTypeCode(_0_school._d_GestionEtudiants)
omniORB.registerType(GestionEtudiants._NP_RepositoryId, _0_school._d_GestionEtudiants, _0_school._tc_GestionEtudiants)

# GestionEtudiants operations and attributes
GestionEtudiants._d_enregistrerEtudiant = ((omniORB.typeMapping["IDL:school/Etudiant:1.0"], ), (), None)
GestionEtudiants._d_modifierEtudiant = (((omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0)), (), None)
GestionEtudiants._d_lireEtudiantsParPromotion = (((omniORB.tcInternal.tv_string,0), ), (omniORB.typeMapping["IDL:school/EtudiantSeq:1.0"], ), None)

# GestionEtudiants object reference
class _objref_GestionEtudiants (CORBA.Object):
    _NP_RepositoryId = GestionEtudiants._NP_RepositoryId

    def __init__(self, obj):
        CORBA.Object.__init__(self, obj)

    def enregistrerEtudiant(self, *args):
        return self._obj.invoke("enregistrerEtudiant", _0_school.GestionEtudiants._d_enregistrerEtudiant, args)

    def modifierEtudiant(self, *args):
        return self._obj.invoke("modifierEtudiant", _0_school.GestionEtudiants._d_modifierEtudiant, args)

    def lireEtudiantsParPromotion(self, *args):
        return self._obj.invoke("lireEtudiantsParPromotion", _0_school.GestionEtudiants._d_lireEtudiantsParPromotion, args)

omniORB.registerObjref(GestionEtudiants._NP_RepositoryId, _objref_GestionEtudiants)
_0_school._objref_GestionEtudiants = _objref_GestionEtudiants
del GestionEtudiants, _objref_GestionEtudiants

# GestionEtudiants skeleton
__name__ = "school__POA"
class GestionEtudiants (PortableServer.Servant):
    _NP_RepositoryId = _0_school.GestionEtudiants._NP_RepositoryId


    _omni_op_d = {"enregistrerEtudiant": _0_school.GestionEtudiants._d_enregistrerEtudiant, "modifierEtudiant": _0_school.GestionEtudiants._d_modifierEtudiant, "lireEtudiantsParPromotion": _0_school.GestionEtudiants._d_lireEtudiantsParPromotion}

GestionEtudiants._omni_skeleton = GestionEtudiants
_0_school__POA.GestionEtudiants = GestionEtudiants
omniORB.registerSkeleton(GestionEtudiants._NP_RepositoryId, GestionEtudiants)
del GestionEtudiants
__name__ = "school"

#
# End of module "school"
#
__name__ = "student_idl"

_exported_modules = ( "school", )

# The end.
