# DO NOT EDIT THIS FILE!
#
# Python module school__POA generated by omniidl

import omniORB
omniORB.updateModule("school__POA")

# ** 1. Stub files contributing to this module
import student_idl

# ** 2. Sub-modules

# ** 3. End
